// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Enable provider debug logging (logs to file terraform-provider-mssql.log)
func GetDebug(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "mssql:debug")
}
