# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .login import *
from .provider import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_mssql.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_mssql.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "mssql",
  "mod": "index/login",
  "fqn": "pulumi_mssql",
  "classes": {
   "mssql:index/login:Login": "Login"
  }
 },
 {
  "pkg": "mssql",
  "mod": "index/user",
  "fqn": "pulumi_mssql",
  "classes": {
   "mssql:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "mssql",
  "token": "pulumi:providers:mssql",
  "fqn": "pulumi_mssql",
  "class": "Provider"
 }
]
"""
)
