// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mssql.Outputs
{

    [OutputType]
    public sealed class UserServerLogin
    {
        /// <summary>
        /// The password of the SQL Server login. Can also be sourced from the `MSSQL_PASSWORD` environment variable.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// The username of the SQL Server login. Can also be sourced from the `MSSQL_USERNAME` environment variable.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private UserServerLogin(
            string password,

            string username)
        {
            Password = password;
            Username = username;
        }
    }
}
