// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mssql.Outputs
{

    [OutputType]
    public sealed class UserServerAzureLogin
    {
        /// <summary>
        /// The client ID of the principal used to login to the SQL Server. Can also be sourced from the `MSSQL_CLIENT_ID` environment variable.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The client secret of the principal used to login to the SQL Server. Can also be sourced from the `MSSQL_CLIENT_SECRET` environment variable.
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// The tenant ID of the principal used to login to the SQL Server. Can also be sourced from the `MSSQL_TENANT_ID` environment variable.
        /// </summary>
        public readonly string TenantId;

        [OutputConstructor]
        private UserServerAzureLogin(
            string clientId,

            string clientSecret,

            string tenantId)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            TenantId = tenantId;
        }
    }
}
