// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mssql.Inputs
{

    public sealed class LoginServerArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Azure AD login for managing the database resources. The attributes supported in the `azure_login` block is detailed below.
        /// </summary>
        [Input("azureLogin")]
        public Input<Inputs.LoginServerAzureLoginArgs>? AzureLogin { get; set; }

        /// <summary>
        /// The host of the SQL Server. Changing this forces a new resource to be created.
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// SQL Server login for managing the database resources. The attributes supported in the `login` block is detailed below.
        /// </summary>
        [Input("login")]
        public Input<Inputs.LoginServerLoginArgs>? Login { get; set; }

        /// <summary>
        /// The port of the SQL Server. Defaults to `1433`. Changing this forces a new resource to be created.
        /// </summary>
        [Input("port")]
        public Input<string>? Port { get; set; }

        public LoginServerArgs()
        {
        }
    }
}
